version: '3.8'
services:
    redis:
      container_name: flixnet-redis
      image: "redis:alpine"
      command: redis-server
      ports:
        - "$REDIS_PORT:$REDIS_PORT"
      volumes:
        - $REDIS_EXTERNAL_LOC
    app:
      container_name: flixnet-app
      image: ericmargules/se452-flixnet:latest
      env_file: ./.env
      ports:
          - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
      environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:h2:mem:se452dbdev",
            "spring.jpa.show-sql" : true,
            "spring.jpa.defer-datasource-initialization" : true,
            "spring.redis.host" : "localhost",
            "spring.redis.port" : "6379"
          }'         