spring:
  profiles:
    active: dev 
  main:
    allow-bean-definition-overriding: true

flixnet:
  swagger:
    openapi: 3.0.1
    version: 1.0.0
    title: SE452 Group4 FlixNet Swagger Documentation
    description: The following are endpoint definitions for the functionality of FlixNet, a theatre management system.

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true