environment: development

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url:  jdbc:h2:mem:se452dbdev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  #Default redis host and port    
  redis:
    host: localhost
    port: 6379