environment: production

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url:  jdbc:h2:mem:se452dbprod
  jpa:
    show-sql: true
    defer-datasource-initialization: true