environment: development

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url:  jdbc:h2:mem:se452dbdev
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379